### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alair069** [NetherTechnology/SAO-System#1]
20:56:27 [ERROR] Could not load 'C:\Users\Alair\Desktop\Server\PocketMine-MP-api3-network-mcpe-1.1\plugins\SAO-System-master' in folder 'C:\Users\Alair\Desktop\Server\PocketMine-MP-api3-network-mcpe-1.1\plugins\': yaml_parse(): scanning error encountered during parsing: found a tab character that violate intendation (line 10, column 1), context while scanning a plain scalar (line 9, column 16)
20:56:27 [CRITICAL] ErrorException: "yaml_parse(): scanning error encountered during parsing: found a tab character that violate intendation (line 10, column 1), context while scanning a plain scalar (line 9, column 16)" (EXCEPTION) in "/src/pocketmine/plugin/PluginDescription" at line 55

I am a tester of your plugins with a lot of pride .. Please do not be angry because I post the errors here for you ..

**Comment by KitrosMC** [comment]
I wont angry,I need to thank you bro.

**Comment by KitrosMC** [comment]
But it is still in construction, I will test and fix it after I finished it.

**Comment by alair069** [comment]
Okay ,Do you have a social network to talk to?

**Comment by KitrosMC** [comment]
Twitter: NetherTech

**Comment by alair069** [comment]
Pls Release the DM for @AnonimoYT1995

**Comment by alair069** [comment]
![Uploading Logo Pack Massive Pack - TempoArts.jpg…]()

I made this soon for you
